# Generated by Django 5.1.2 on 2025-01-16 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course', models.CharField(blank=True, max_length=250, null=True)),
                ('Description', models.CharField(blank=True, max_length=500, null=True)),
                ('FeesDetails', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=80)),
                ('Password', models.CharField(max_length=20)),
                ('Type', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.CharField(max_length=200)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=40)),
                ('COURSE', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smart_app.coursetable')),
            ],
        ),
        migrations.CreateModel(
            name='ClassTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClassName', models.CharField(blank=True, max_length=30, null=True)),
                ('sem', models.CharField(blank=True, max_length=30, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_app.department')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_app.login')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField()),
                ('review', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_app.login')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('place', models.CharField(max_length=20)),
                ('post', models.CharField(max_length=20)),
                ('pin', models.IntegerField()),
                ('phone', models.BigIntegerField()),
                ('email', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('DEPARTMENT_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_app.department')),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_app.login')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AdmissionNo', models.IntegerField(blank=True, null=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('photo', models.ImageField(upload_to='')),
                ('place', models.CharField(max_length=30)),
                ('post', models.CharField(max_length=30)),
                ('pin', models.IntegerField()),
                ('phone', models.BigIntegerField()),
                ('email', models.CharField(max_length=30)),
                ('DEPARTMENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_app.department')),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_app.login')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Request', models.CharField(blank=True, max_length=250, null=True)),
                ('Date', models.CharField(blank=True, max_length=250, null=True)),
                ('Time', models.CharField(blank=True, max_length=250, null=True)),
                ('STUDENT', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smart_app.student')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(max_length=300)),
                ('date', models.CharField(max_length=300)),
                ('reply', models.CharField(max_length=300)),
                ('STUDENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_app.student')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(max_length=20)),
                ('Attendance', models.CharField(max_length=20)),
                ('STUDENT_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_app.student')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(blank=True, max_length=250, null=True)),
                ('DEPARTMENT', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smart_app.department')),
            ],
        ),
        migrations.CreateModel(
            name='AllocationTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(auto_now_add=True)),
                ('STAFF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_app.staff')),
                ('SUBJECT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_app.subjecttable')),
            ],
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Day', models.CharField(blank=True, max_length=250, null=True)),
                ('Period', models.CharField(blank=True, max_length=250, null=True)),
                ('SUBJECT', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smart_app.subjecttable')),
                ('TEACHER', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smart_app.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Timetable1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=10)),
                ('CLASS', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smart_app.classtable')),
                ('slot_10_11', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_10_11', to='smart_app.subjecttable')),
                ('slot_11_12', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_11_12', to='smart_app.subjecttable')),
                ('slot_1_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_1_2', to='smart_app.subjecttable')),
                ('slot_2_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_2_3', to='smart_app.subjecttable')),
                ('slot_3_4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_3_4', to='smart_app.subjecttable')),
                ('slot_9_10', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_9_10', to='smart_app.subjecttable')),
            ],
        ),
    ]
