# Generated by Django 5.1.2 on 2025-01-17 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='Period',
            field=models.CharField(blank=True, choices=[('slot_9_10', 'slot_9_10'), ('slot_10_11', 'slot_10_11'), ('slot_11_12', 'slot_11_12'), ('slot_1_2', 'slot_1_2 '), ('slot_2_3', 'slot_2_3 '), ('slot_3_4', 'slot_3_4')], max_length=250, null=True),
        ),
    ]
