# Generated by Django 5.1.2 on 2025-01-17 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_app', '0002_attendance_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='CLASS',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='smart_app.classtable'),
            preserve_default=False,
        ),
    ]
