# Generated by Django 5.1.2 on 2025-01-25 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_app', '0005_rename_attendance_attendancetable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancetable',
            name='Date',
            field=models.DateTimeField(max_length=20),
        ),
    ]
