# Generated by Django 5.1.2 on 2025-01-25 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_app', '0006_alter_attendancetable_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancetable',
            name='Date',
            field=models.DateField(max_length=20),
        ),
    ]
